version: '3.1'

networks:
  rti:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/24

services:
  eventstore:
    image: eventstore/eventstore:21.10.1-bionic
    restart: always
    environment:
      EVENTSTORE_START_STANDARD_PROJECTIONS: "True"
      EVENTSTORE_RUN_PROJECTIONS: All
      EVENTSTORE_MEM_DB: "False"
      EVENTSTORE_INSECURE: "True"
      EVENTSTORE_ENABLE_EXTERNAL_TCP: "True"
      EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: "True"
    networks:
      rti:
    ports:
      - 1112:1112
      - 2112:2112
      - 1113:1113
      - 2113:2113
    volumes:
      - ./data:/var/lib/eventstore
      - ./logs:/var/log/eventstore 

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
    restart: always
    networks:
      rti:
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "9x1P:JsNhEC%42ZWO"
    ports:
      - 1433:1433

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      rti:
  
  kafka:
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      rti:
    depends_on:
      - zookeeper
  
  redis:
    image: redis:6.2.6-alpine3.15
    restart: always
    networks:
      rti:
    ports:
      - 6379:6379

  mongodb:
    image: mongo:5.0.6-focal
    restart: always
    networks:
      rti:
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: changeit
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    networks:
      rti:
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://admin:changeit@mongodb:27017/"
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"

      ME_CONFIG_MONGODB_AUTH_DATABASE: admin

      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: changeit

      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: changeit

      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: changeit
    ports:
      - 8081:8081
    links:
      - mongodb
    depends_on:
      - mongodb
